language: android
android:
    components:
        # The BuildTools version used by this project and CastCompanionLibrary
        - build-tools-23.0.1

        # The SDK version used to compile this project
        - android-22
        - android-23

        # Additional components
        - extra-android-support
        - extra-google-google_play_services
        - extra-google-m2repository
        - extra-android-m2repository

        # Emulators needed to run tests (eventually)
        #- sys-img-armebi-v7a-android-23
        #- sys-x86-android-tv-1

script: ./gradlew build --stacktrace