language: android
android:
    components:
        # The BuildTools version used by this project and CastCompanionLibrary
        - build-tools-22.0.1

        # The SDK version used to compile this project
        - android-22

        # Additional components
        - extra-android-support
        - extra-google-google_play_services

        # Emulators needed to run tests (eventually)
        #- sys-img-armebi-v7a-android-22
        #- sys-x86-android-tv-1

script: ./gradlew build --stacktrace